3akar/Akar/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobiles { get; set; }
        public string Whatsapps { get; set; }
        public string LandLines { get; set; }
        public bool Active { get; set; }
        public string UserId { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string CompanyEmail { get; set; }
        public string Address { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}

3akar/Akar/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Akar.Models;
using Microsoft.AspNet.Identity;

namespace Akar.Controllers
{
    public class CompaniesController : Controller
    {
        private Akar20180617043702_dbEntities db = new Akar20180617043702_dbEntities();

        // GET: Companies
        public ActionResult Index()
        {
            var companies = db.Companies.Include(c => c.AspNetUser);
            return View(companies.ToList());
        }

        public ActionResult Show(int id)
        {
            var imageData = db.Brokers.Find(id).Picture;

            return File(imageData, "image/jpg");
        }
        public ActionResult Approve(int id)
        {
            var Broker = db.Brokers.Find(id);
            Broker.Approved = true;
            db.AspNetUsers.Find(Broker.UserId).EmailConfirmed = true;
            db.SaveChanges();
            return View("ManageWaitingList");
        }
        public ActionResult Deny(int id)
        {
            var Broker = db.Brokers.Find(id);
            Broker.Approved = false;
            db.AspNetUsers.Find(Broker.UserId).EmailConfirmed = false;
            db.SaveChanges();
            return View("ManageWaitingList");
        }

        public ActionResult ManageWaitingList()
        {

            List<Broker> Brokers = null;
            var currentUser = User.Identity.GetUserId();
            var currentCompany = (db.Companies.Where(c => c.UserId == currentUser).ToList().Count > 0) ? db.Companies.Where(c => c.UserId == currentUser).First() : null;
            if (currentCompany != null)
                Brokers = db.Brokers.Where(c => c.CompanyId == currentCompany.Id).ToList();

            ViewBag.Broker = Brokers;
            return View();
        }


        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Mobiles,Whatsapps,LandLines,Active,UserId,CompanyLogo,CompanyEmail,Address")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", company.UserId);
            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", company.UserId);
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Mobiles,Whatsapps,LandLines,Active,UserId,CompanyLogo,CompanyEmail,Address")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", company.UserId);
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

3akar/Akar/Views/Companies/Create.cshtml
@model Akar.Models.Company

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Company</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Mobiles, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobiles, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobiles, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Whatsapps, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Whatsapps, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Whatsapps, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LandLines, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LandLines, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LandLines, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Active)
                        @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyLogo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyLogo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyLogo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

3akar/Akar/Views/Companies/Delete.cshtml
@model Akar.Models.Company

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Company</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Mobiles)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Mobiles)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Whatsapps)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Whatsapps)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LandLines)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LandLines)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CompanyLogo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CompanyLogo)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CompanyEmail)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CompanyEmail)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

3akar/Akar/Views/Companies/Details.cshtml
@model Akar.Models.Company

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Company</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Mobiles)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Mobiles)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Whatsapps)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Whatsapps)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LandLines)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LandLines)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CompanyLogo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CompanyLogo)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CompanyEmail)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CompanyEmail)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

3akar/Akar/Views/Companies/Edit.cshtml
@model Akar.Models.Company

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Company</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Mobiles, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobiles, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobiles, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Whatsapps, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Whatsapps, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Whatsapps, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LandLines, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LandLines, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LandLines, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Active)
                        @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyLogo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyLogo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyLogo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

3akar/Akar/Views/Companies/Index.cshtml
@model IEnumerable<Akar.Models.Company>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobiles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Whatsapps)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LandLines)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyLogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobiles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Whatsapps)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LandLines)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyLogo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

3akar/Akar/Views/Companies/ManageWaitingList.cshtml
@{
    ViewBag.Title = "Waiting List";
}
<h2>Brokers Waiting List</h2>
@if (ViewBag.Broker != null)
{
    foreach (Akar.Models.Broker broker in ViewBag.Broker)
    {
        <div class="row thumbnail" style=" margin:15px;">
            <div class="col-md-1 col-sm-1 thumbnail thumbnail-property">
                <a>
                    <img width="150" height="150" src='@Url.Action("Show", "Companies", new { id = broker.Id })' />
                </a>
            </div>
            <div class="header col-md-9 col-sm-9">
                <div class="left">
                    <span>Name: @broker.Name </span><br />
                    <span>Email: @broker.Mail </span><br />
                    <span>Mobiles: @broker.Mobiles </span><br />
                    <span>Whatsapps: @broker.Whatsapps </span><br />
                    <span>Landlines: @broker.Landlines </span>
                </div>
            </div>
            <div class="col-md-1 col-sm-1">
                <a href='@Url.Action("Approve", "Companies", new { id = broker.Id })'>
                    <span>Approve</span>
                </a>
            </div>
            <div class="col-md-1 col-sm-1">
                <a href='@Url.Action("Deny", "Companies", new { id = broker.Id })'>
                    <span>Deny</span>
                </a>
            </div>
        </div>
    }
}
else
{
    <h3>No Current Brokers Wiating List</h3>
}