3akar/Akar/Models/Advertisement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.Adimages = new HashSet<Adimage>();
        }
    
        public int Id { get; set; }
        public string AdTitle { get; set; }
        public Nullable<int> PropertyLocationId { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> Sale_Rent { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> BedRooms { get; set; }
        public Nullable<int> BathRooms { get; set; }
        public Nullable<int> LivingRooms { get; set; }
        public Nullable<bool> MasterRoom { get; set; }
        public Nullable<int> Reciption { get; set; }
        public Nullable<bool> DressingRooms { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public Nullable<double> Price { get; set; }
        public string AdDescription { get; set; }
        public Nullable<bool> Paymentfacilities { get; set; }
        public Nullable<int> Furnish { get; set; }
        public Nullable<int> PaymentDuration { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public string UserId { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adimage> Adimages { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PropertyLocation PropertyLocation { get; set; }
        public virtual PropertyType PropertyType { get; set; }
    }
}

3akar/Akar/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Akar.Models;
using Microsoft.AspNet.Identity;
namespace Akar.Controllers
{
    public class AdvertisementsController : Controller
    {
        private Akar20180617043702_dbEntities db = new Akar20180617043702_dbEntities();

        // GET: Advertisements
        public ActionResult Index()
        {
            return View(db.Advertisements.ToList());
        }
        public ActionResult upload(string id ,string AdCode)
        {
            string[] s = id.Split('_');
            ViewBag.ImageName = s[0];
            ViewBag.adCode = s[1];
            return View();
        }

        [HttpPost]
        public ActionResult upload(string RoomName, bool C3d, string AdCode, HttpPostedFileBase file)
        {
            Adimage Image = new Adimage();
            Image.RoomName = RoomName;
            Image.C3d = C3d;
            Image.AdCode = AdCode;
            try
            {
                var files = Request.Files[0];
                var hpf = files.InputStream;
                if (hpf.Length > 0)
                {
                    using (System.IO.MemoryStream ms = new System.IO.MemoryStream())
                    {
                        hpf.CopyTo(ms);
                        Image.Image = ms.GetBuffer();
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            if (ModelState.IsValid)
            {
                db.Adimages.Add(Image);
                db.SaveChanges();
                return Json(new
                {
                    status = "success2"
                });
            }
            return Json(new
            {
                status = "failure",
                formErrors = ModelState.Select(kvp => new { key = kvp.Key, errors = kvp.Value.Errors.Select(e => e.ErrorMessage) })
            });
        }
        public ActionResult ShowImgbyID(string id)
        {
            var imageData = db.Adimages.Where(c => c.Id.ToString() == id && c.RoomName != "Main").FirstOrDefault();
            if (imageData != null)
            {
                if (Request.IsAjaxRequest())
                {
                    var filennn = DateTime.Now.ToString().Replace("/", "").Replace(":", "") + imageData.RoomName + ".jpeg";
                    var filename = Path.GetFileName(filennn);
                    var path = Path.Combine(Server.MapPath("~/Content/assets/img/Temp/"), filennn);
                    FileStream fs = new FileStream(path, FileMode.OpenOrCreate);
                    fs.Write(imageData.Image, 0, imageData.Image.Length);
                    return Json("http://"+ Request.Url.Authority + "/Content/assets/img/Temp/" + filennn, JsonRequestBehavior.AllowGet);
                }
                
                return File(imageData.Image, "image/jpg");
            }
            else
            {
                string path = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content\\assets\\img", "No_Image_Available.png");
                FileStream fs = null;
                try
                {
                    fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                    FileStreamResult result = new FileStreamResult(fs, "image/png");

                    fs = null;
                    result.FileDownloadName = "image.png";
                    return result;
                }
                finally
                {
                    if (fs != null)
                        fs.Dispose();
                }

            }
        }
        public ActionResult ShowMain(string id)
        {
            var imageData = db.Adimages.Where(c => c.AdCode == id.ToString() && c.RoomName == "Main").FirstOrDefault();
            if (imageData != null)
                return File(imageData.Image, "image/jpg");
            else
            {
                string path = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content\\assets\\img", "No_Image_Available.png");
                FileStream fs = null;
                try
                {
                    fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                    FileStreamResult result = new FileStreamResult(fs, "image/png");

                        fs = null;
                    result.FileDownloadName = "image.png";
                    return result;
                }
                finally
                {
                    if (fs != null)
                        fs.Dispose();
                }

            }
        }
        // GET: Advertisements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }
        public ActionResult AddAdvertViewModel2()
        {
            ViewBag.Locations = db.PropertyLocations.Select(c => new { Id = c.Id, Name = c.Governorate + " - " + c.District + (string.IsNullOrEmpty(c.Project) ? "" : " - " + c.Project) }).ToList();
            ViewBag.types = db.PropertyTypes.Select(c => new { Id = c.Id, EName = c.EnglishName, AName = c.ArabicName }).ToList();
            ViewBag.AdCode = (db.Advertisements.ToList()[(db.Advertisements.ToList().Count-1)].Id+1).ToString() + Guid.NewGuid().ToString().Split('-')[3];

            return PartialView();
        }
        public ActionResult AddAdvertViewModel()
        {
            ViewBag.Locations = db.PropertyLocations.Select(c => new { Id = c.Id, Name = c.Governorate + " - " + c.District + (string.IsNullOrEmpty(c.Project) ? "" : " - " + c.Project) }).ToList();
            ViewBag.types = db.PropertyTypes.Select(c => new { Id = c.Id, EName = c.EnglishName, AName = c.ArabicName }).ToList();
            ViewBag.AdCode = (db.Advertisements.ToList()[(db.Advertisements.ToList().Count-1)].Id+1).ToString() + Guid.NewGuid().ToString().Split('-')[3];

            return PartialView();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [HandleError]
        public ActionResult AddAdvertViewModel2([Bind(Include = "Id,AdTitle,PropertyLocationId,PropertyTypeId,Sale_Rent,Area,BedRooms,BathRooms,LivingRooms,MasterRoom,Reciption,DressingRooms,Floor,Elevator,Price,AdDescription,Paymentfacilities,Furnish,PaymentDuration,DownPayment,Code")] Advertisement advertisement)
        {
            var CurrentUser = User.Identity.GetUserName();
            var currentuserid = db.AspNetUsers.Where(c => c.UserName == CurrentUser); 
            var images = db.Adimages.Where(c => c.AdCode == advertisement.Code);
            foreach(var image in images)
            {
                image.AdId = advertisement.Id;
            }
            advertisement.UserId = currentuserid.FirstOrDefault()?.Id;
            if (ModelState.IsValid)
            {
                db.Advertisements.Add(advertisement);
                db.SaveChanges();
                return Json(new
                {
                    status = "success"
                });
            }
            return Json(new
            {
                status = "failure",
                formErrors = ModelState.Select(kvp => new { key = kvp.Key, errors = kvp.Value.Errors.Select(e => e.ErrorMessage) })
            });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [HandleError]
        public ActionResult AddAdvertViewModel([Bind(Include = "Id,AdTitle,PropertyLocationId,PropertyTypeId,Sale_Rent,Area,BedRooms,BathRooms,LivingRooms,MasterRoom,Reciption,DressingRooms,Floor,Elevator,Price,AdDescription,Paymentfacilities,Furnish,PaymentDuration,DownPayment,Code")] Advertisement advertisement)
        {
            var CurrentUser = User.Identity.GetUserId();
            var images = db.Adimages.Where(c => c.AdCode == advertisement.Code);
            foreach(var image in images)
            {
                image.AdId = advertisement.Id;
            }
            advertisement.UserId = CurrentUser;
            if (ModelState.IsValid)
            {
                db.Advertisements.Add(advertisement);
                db.SaveChanges();
                return Json(new
                {
                    status = "success"
                });
            }
            return Json(new
            {
                status = "failure",
                formErrors = ModelState.Select(kvp => new { key = kvp.Key, errors = kvp.Value.Errors.Select(e => e.ErrorMessage) })
            });
        }

        // GET: Advertisements/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Advertisements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,PropertyLocationId,PropertyTypeId,Sale_Rent,Area,BedRooms,BathRooms,LivingRooms,MasterRoom,Reciption,DressingRooms,Floor,Elevator,Price,Description,Paymentfacilities,Furnish,PaymentDuration,DownPayment")] Advertisement advertisement)
        {
            if (ModelState.IsValid)
            {
                db.Advertisements.Add(advertisement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(advertisement);
        }

        // GET: Advertisements/Edit/5
        public ActionResult Edit(int? id)
        {

3akar/Akar/Views/Advertisements/Delete.cshtml
@model Akar.Models.Advertisement

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Advertisement</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PropertyLocationId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PropertyLocationId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PropertyTypeId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PropertyTypeId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Sale_Rent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Sale_Rent)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Area)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Area)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.BedRooms)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.BedRooms)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.BathRooms)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.BathRooms)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LivingRooms)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LivingRooms)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MasterRoom)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MasterRoom)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Reciption)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Reciption)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DressingRooms)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DressingRooms)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Floor)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Floor)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Elevator)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Elevator)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Paymentfacilities)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Paymentfacilities)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Furnish)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Furnish)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PaymentDuration)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PaymentDuration)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DownPayment)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DownPayment)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

3akar/Akar/Views/Advertisements/Details.cshtml
@model Akar.Models.Advertisement

<script src="~/vendor/photo-sphere-viewer.min.js"></script>
<script src="~/vendor/marzipano.js"></script>
<script src="~/vendor/three.min.js"></script>
<style>
    img {
        cursor: zoom-in;
    }

    .modal-body {
        overflow-y:;
    }

    .modal {
        text-align: center;
    }

        .modal .modal-content {
            position: fixed;
            z-index: 99999;
            left: -20em;
            top: -30em;
            /*width: -webkit-fill-available;
            height: -webkit-fill-available;*/
            overflow: auto;
        }

    @@media screen and (min-width: 768px) {
        .modal:before {
            display: inline-block;
            vertical-align: middle;
            content: " ";
            height: 100%;
        }
    }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }
</style>
<script>
    function sleep(delay) {
        var start = new Date().getTime();
        while (new Date().getTime() < start + delay);
    }

    $(function () {
        $('.imgN').on('click', function () {
            $('.enlargeImageModalSource').attr('src', $(this).attr('src'));
            $('#enlargeImageModal').modal('show');
        });
    });
    $(function () {

        $('.img3d').on('click', function () {
            $('#enlargeImageModal3d').modal('show');
            $.ajax({
                url: $(this).attr('src'),
                type: "GET",
                dataType: "json",
                success: function (dataa, errorMessage) {
                    var div = document.getElementById('dtaimg');
                    var PSV = new PhotoSphereViewer({
                        panorama: dataa,
                        container: div,
                        time_anim: 0,
                        minFilter: THREE.NearestFilter,
                        loading_txt: 'Loading',
                        autoload: false,
                    });
                    sleep(1000)
                    PSV.load();
                },
                error: function (dataa, errorMessage) {


                }
            });
            //$('.enlargeImageModalSource3d').attr('src', $(this).attr('src'));

        });
    });
</script>

<div class="modal fade" id="enlargeImageModal" tabindex="-1" role="dialog" aria-labelledby="enlargeImageModal" aria-hidden="true">
    <div class="modal-dialog modal-lg " role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <img src="" class="enlargeImageModalSource" style="width: auto;position:page;">
            </div>
        </div>
    </div>
</div>
<div class="modal fade dtaimgclass" id="enlargeImageModal3d" tabindex="-1" role="dialog" aria-labelledby="enlargeImageModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <div id="dtaimg" style="height:35vw;width:80vw;">

                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="col-md-12 col-sm-12">
        <div class="col-md-2 col-sm-2">
            <h2 style="direction:ltr;position:relative;left=0px">

                @Html.DisplayFor(Model => Model.AdTitle) :
            </h2>
        </div>
        <div class="col-md-10 col-sm-10">
            <h2 style="direction:ltr;position:relative;left=0px">
                @Html.DisplayFor(Model => Model.Price) جم
            </h2>
        </div>
        <div class="col-md-12">
            <div class="col-md-2">
                <img class="imgN" style="width:14vw; height:auto;" src="@Url.Action("ShowMain", "Advertisements")/@Model.Code">
            </div>
            <div class="col-md-8">
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.AdDescription) : @Html.DisplayFor(Model => Model.AdDescription)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.BathRooms) : @Html.DisplayFor(Model => Model.BathRooms)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.BedRooms) : @Html.ValueFor(Model => Model.BedRooms)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.Floor) : @Html.DisplayFor(Model => Model.Floor)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.Furnish) : @Html.DisplayFor(Model => Model.Furnish)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.LivingRooms) : @Html.DisplayFor(Model => Model.LivingRooms)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.Reciption) : @Html.DisplayFor(Model => Model.Reciption)
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.DressingRooms) : @{ if (@Html.ValueFor(Model => Model.DressingRooms).ToString() == "True")
                        {
                            <span>Yes</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    }
                </div>

                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.Elevator) : @{ if (@Html.ValueFor(Model => Model.Elevator).ToString() == "True")
                        {
                            <span>Yes</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    }
                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.MasterRoom) : @{ if (@Html.ValueFor(Model => Model.MasterRoom).ToString() == "True")
                        {
                            <span>Yes</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    }
                </div>

                <div class="col-md-6 col-sm-6">
                    @Html.LabelFor(Model => Model.Paymentfacilities) :@{ if (@Html.ValueFor(Model => Model.Paymentfacilities).ToString() == "True")
                        {
                            <span>Yes</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    }
                </div>
            </div>
        </div>
        <div align="center">
            <h2>Album</h2>
        </div>
        <div class="slideshow-container">
            @{
                int imgcounter = 0;
                foreach (var img in Model.Adimages)
                {
                    if (img.RoomName != "Main")
                    {
                        <div class="mySlides fade">
                            <div class="numbertext">@imgcounter</div>
                            @if (!img.C3d)
                            {
                                <img class="imgN" style="width:100%; height:auto;" src="@Url.Action("ShowImgbyID", "Advertisements")/@img.Id">

                            }
                            else
                            {

                                    <img class="img3d" style="width:100%; height:auto;" src="@Url.Action("ShowImgbyID", "Advertisements")/@img.Id">

                            }
                            <div class="text">@img.RoomName</div>
                            @{imgcounter += 1;
                            }
                        </div>


                    }
                }

                <!-- Next and previous buttons -->
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>

                <br>
                <div style="text-align:center">
                    @for (int i = 0; i < imgcounter; i++)
                    {
                        <span class="dot" onclick="currentSlide(@i)"></span>

                    }
                </div>
            }
        </div>
    </div>
</div>

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
    }
</script>
<style>
    .slideshow-container {
        max-width: 1000px;
        position: relative;
        margin: auto;
    }

    /* Next & previous buttons */
    .prev, .next {
        cursor: pointer;
        position: absolute;
        top: 50%;
        width: auto;
        padding: 16px;
        margin-top: -22px;
        color: white;
        font-weight: bold;
        font-size: 18px;
        transition: 0.6s ease;
        border-radius: 0 3px 3px 0;
        background: #ae0303;
    }

    /* Position the "next button" to the right */
    .next {
        right: 0;
        border-radius: 3px 0 0 3px;
    }

        /* On hover, add a black background color with a little bit see-through */
        .prev:hover, .next:hover {
            background-color: rgba(0,0,0,0.8);
        }

    /* Caption text */
    .text {
        color: #ae0303;
        font-size: 15px;
        padding: 11.0px 12px;
        position: absolute;
        bottom: 8px;
        width: 100%;
        text-align: center;
    }

    /* Number text (1/3 etc) */
    .numbertext {
        color: #f2f2f2;
        font-size: 12px;
        padding: 8px 12px;
        position: absolute;
        top: 0;
    }

    /* The dots/bullets/indicators */
    .dot {
        cursor: pointer;
        height: 15px;
        width: 15px;
        margin: -4px 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
    }

        .active, .dot:hover {
            background-color: #717171;
        }

    /* Fading animation */
    .fade {
        opacity:1 !important;
        -webkit-animation-name: fade !important;
        -webkit-animation-duration: 1.5s !important;
        animation-name: fade !important;
        animation-duration: 1.5s !important;
    }

    @@-webkit-keyframes fade {
        from {
            opacity: .4
        }

        to {
            opacity: 1
        }
    }

    @@keyframes fade {
        from {
            opacity: .4
        }

        to {
            opacity: 1
        }
    }

    /* On smaller screens, decrease text size */
    @@media only screen and (max-width: 300px) {
        .prev, .next, .text {
            font-size: 11px
        }
    }
</style>